trigger:
- master
- develop
- release/*
- hotfix/*
- feature/*

pool:
  name: Default
  demands:
  - msbuild
  - visualstudio
  - vstest

variables:
  AssemblyVersion: '0.0.1'
  solution: 'src/LeanCostIntegration.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

jobs:
- job: Phase_1
  displayName: Phase 1
  cancelTimeoutInMinutes: 1
  pool:
    name: Default
  steps:

  - checkout: self
    clean: true

  - task: LibreOfficeKiller@0
    name: LibreOfficeKiller_1
    displayName: 'LibreOfficeKiller '

  - task: SonarCloudPrepare@1
    displayName: Prepare analysis on SonarCloud
    enabled: False
    inputs:
      SonarCloud: 924aab99-64b6-4bcd-bab3-8949d1b11273
      organization: alkampfergit-github
      projectKey: DocumentStore
      projectName: DocumentStore
      projectVersion: $(AssemblyVersion)

  - task: GitVersion@1
    name: Run_GitVersion
    displayName: 'GitVersion '
    inputs:
      BuildNamePrefix: Jarvis DocumentStore - CI

  - task: NuGetToolInstaller@1
    displayName: Use NuGet 5.x
    inputs:
      versionSpec: 5.x
      checkLatest: true

  - task: NuGetCommand@2
    name: NuGetInstaller_3
    displayName: NuGet restore **\*.sln
    inputs:
      solution: '**\*.sln'
      selectOrConfig: config
      nugetConfigPath: src/NuGet.Config

  - task: VSBuild@1
    name: VSBuild_4
    displayName: Build solution **\*.sln
    inputs:
      platform: $(BuildPlatform)
      configuration: $(BuildConfiguration)

  - task: VSTest@1
    name: VSTest_5
    displayName: Test Assemblies **\$(BuildConfiguration)\net461\*test*.dll;-:**\obj\**
    continueOnError: True
    inputs:
      testAssembly: '**\$(BuildConfiguration)\net461\*test*.dll;-:**\obj\**'
      codeCoverageEnabled: true
      vsTestVersion: latest
      platform: $(BuildPlatform)
      configuration: $(BuildConfiguration)

  - task: SonarCloudAnalyze@1
    displayName: Run Code Analysis
    enabled: False

  - task: SonarCloudPublish@1
    displayName: Publish Quality Gate Result
    enabled: False
    inputs:
      pollingTimeoutSec: 3000

  



