using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using Jarvis.DocumentStore.Client.Model;
using Jarvis.DocumentStore.JobsHost.Helpers;
using Jarvis.DocumentStore.Shared.Jobs;
using Path = Jarvis.DocumentStore.Shared.Helpers.DsPath;
using File = Jarvis.DocumentStore.Shared.Helpers.DsFile;
using System.Linq;

namespace Jarvis.DocumentStore.Jobs.PdfThumbnails
{
    public class CreateThumbnailFromPdfOutOfProcessJob : AbstractOutOfProcessPollerJob
    {
        public CreateThumbnailFromPdfOutOfProcessJob(Func<CreateImageFromPdfTask> taskFactory)
        {
            base.PipelineId = "pdf";
            base.QueueName = "pdfThumb";
            _taskFactory = taskFactory;
        }

        private readonly Func<CreateImageFromPdfTask> _taskFactory;

        protected async override Task<ProcessResult> OnPolling(PollerJobParameters parameters, string workingFolder)
        {
            //if this handle already has rasterImage we do not need to do anything
            //we can skip only if this action is not forced or if the pdf was not generated by office
            //because office file can be re-generated due to errors in conversoin (libreoffice or MsOffice)
            if (!IsForced(parameters)
                && !FromPipelineId(parameters, "office")
                && !FromPipelineId(parameters, "htmlzip"))
            {
                var formats = GetFormats(parameters.TenantId, parameters.JobId);
                if (formats.Any(f => f == DocumentFormats.RasterImage))
                    return ProcessResult.Ok;
            }

            String format = parameters.All[JobKeys.ThumbnailFormat];
            Logger.DebugFormat("Conversion for jobId {0} in format {1} starting", parameters.JobId, format);

            var task = _taskFactory();
            var passwords = ClientPasswordSet.GetPasswordFor(parameters.FileName);
            foreach (var password in passwords)
            {
                task.Passwords.Add(password);
            }
            string pathToFile = await DownloadBlob(parameters.TenantId, parameters.JobId, parameters.FileName, workingFolder).ConfigureAwait(false);

            var convertParams = new CreatePdfImageTaskParams()
            {
                Dpi = parameters.GetIntOrDefault(JobKeys.Dpi, 150),
                FromPage = parameters.GetIntOrDefault(JobKeys.PagesFrom, 1),
                Pages = parameters.GetIntOrDefault(JobKeys.PagesCount, 1),
                Format = (CreatePdfImageTaskParams.ImageFormat)Enum.Parse(typeof(CreatePdfImageTaskParams.ImageFormat), format, true)
            };

            await task.Run(
                pathToFile,
                convertParams,
                (i, s) => Write(workingFolder, parameters, format, i, s) //Currying
            ).ConfigureAwait(false);

            Logger.DebugFormat("Conversion of {0} in format {1} done", parameters.JobId, format);
            return ProcessResult.Ok;
        }

        public async Task<Boolean> Write(String workerFolder, PollerJobParameters parameters, String format, int pageIndex, Stream stream)
        {
            var rawFileName = Path.Combine(workerFolder, Path.GetFileNameWithoutExtension(parameters.FileName) + ".page_" + pageIndex + "." + format);
            rawFileName = SanitizeFileNameForLength(rawFileName);
            using (var outStream = File.OpenWrite(rawFileName))
            {
                stream.CopyTo(outStream);
            }

            await AddFormatToDocumentFromFile(
                 parameters.TenantId,
                 parameters.JobId,
                 new DocumentFormat(DocumentFormats.RasterImage),
                 rawFileName,
                 new Dictionary<string, object>()).ConfigureAwait(false);
            return true;
        }
    }
}
